### ISSUE TITLE
Complete. Global. Saturation.

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#10]
Does that means this pack will finish soon?

**Comment by CurlySparkle** [comment]
lol i don't think so, just some improvements

**Comment by mwxmwh** [comment]
I think you can write down the changes so that we can know what was improved.
But if it's bother you,forget it.

**Comment by mwxmwh** [comment]
> lol i don't think so, just some improvements

by the way, do you have any way to solve(only when you press R, the hang up the empty warehouse can show in the third person view) this? just keeping hang up the empty warehouse when the weapons are empty.
