### ISSUE TITLE
M32 grenades and UBGLs could no longer destroy Combine Gunships

### ISSUE THREAD

**Issue by highblaz97** [CurlySparkle/ARC9-COD2019#100]
I remember during earlier updates, grenades from M32 and UBGLs can take down gunships, but now it's no longer possible in current update. What happened to the coding? Can you revert the grenades back to old updates?

**Comment by CurlySparkle** [comment]
is this on the workshop or current version on here? because things been changed and should be able to destroy those

**Comment by highblaz97** [comment]
Hi, sorry for the late reply. Apparently during the day when I commented this, the nades don't affect gunships at all, eventhough it can destroy helicopters.

If you already updated it, then it's alright. I'll check again later.
