### ISSUE TITLE
New issue with smoke grenades

### ISSUE THREAD

**Issue by syahmiasyraff02** [CurlySparkle/ARC9-COD2019#101]
I haven't played GMod for a week or two, and things have changed with the weapon pack since I last played it. Since the release of an update for the Workshop release on the 6th July, the enemy NPCs can see the player behind the smokescreen. It's only when the player is inside the smokescreen where they can't see him/her. I'm pretty sure this issue has been fixed on the latest GitHub commits, but I've yet to take a look at them myself. If it hasn't, well, you know what to do...

**Comment by CurlySparkle** [comment]
nextbots can and will see the player on the smoke due to how complicated their ai setup is so it's not possible to make them not see the player, bust most normal npcs should lost track of the player as soon as its inside the smoke sphere

**Comment by syahmiasyraff02** [comment]
Forget about nexbots, I'm talking about regular NPCs in the OP. As soon as I step out of that smoke sphere, the regular enemy NPCs will see me regardless of whether they are inside or at the opposite side of the smoke sphere.

**Comment by CurlySparkle** [comment]
i mean it's obv they retarget you since you stepping out the smoke, that's just standard gmod jank, either way I don't know how to make it so npcs that are inside the smoke get confused since it just for the player
