### ISSUE TITLE
Duplicate tri-lug muzzle mount and front sight on MP5 FSS Light Barel + Rail cover for Subsonic barrel stays on when equipping angled grips

### ISSUE THREAD

**Issue by ColonelRedips** [CurlySparkle/ARC9-COD2019#104]
I feel kinda dumb for not pointing this out earlier. 
![20240725105140_1](https://github.com/user-attachments/assets/86d9aa8b-1c1c-4052-a27f-85086d0fce93)
![20240725105145_1](https://github.com/user-attachments/assets/518e153e-e106-46b7-841b-632f363b037e)
![20240725105148_1](https://github.com/user-attachments/assets/3a86907d-0b05-4cca-9268-d4dc26805feb)
![20240725105153_1](https://github.com/user-attachments/assets/e0490e19-3804-4ce4-b24f-8eda2ffaffe8)
![20240725110129_1](https://github.com/user-attachments/assets/e9507779-27bc-4598-9ce9-4e7a4a0bd419)

**Comment by CurlySparkle** [comment]
hopefully should be fixed now

**Comment by ColonelRedips** [comment]
Unfortunately both issues pop up for me still. Hope you can fix bodygroups in the LUA file if that helps.
