### ISSUE TITLE
[Follow-Up] M32 grenades and UBGLs could no longer destroy Combine Gunships 

### ISSUE THREAD

**Issue by highblaz97** [CurlySparkle/ARC9-COD2019#105]
https://github.com/user-attachments/assets/2726b2e3-4adf-4692-9ce0-fb249079ba92

Hi again. Just want to follow up from my previous issue. From what I recorded (sorry for the lag), the nades from M32 cannot affect gunships at all (and no, this is not a ragdoll, it's a frozen gunship NPC). Can you check if this issue is at your end too? Thanks.

**Comment by CurlySparkle** [comment]
if this is on the workshop then its been already been fixed just hasn't been pushed the update to the workshop yet

**Comment by highblaz97** [comment]
So I need to download the github version for the fixed version for now? Alright then, I'll try

**Comment by Firmeteran** [comment]
> So I need to download the github version for the fixed version for now? Alright then, I'll try download it.

For now, yeah.
'cus we're been busy _cooking_ stuff in the git and haven't push new update in few weeks.

**Comment by highblaz97** [comment]
https://github.com/user-attachments/assets/0d70161c-f471-49c5-ac93-8f977172e753

So, I've disabled the workshop version, and installed the current git version but I think the problem still persists on gunships. The grenades hit the gunship NPC but couldn't destroy it. Funny that helicopter NPC can be destroyed.

Maybe you can look into the lua files of the GL nades, see if you can edit them so gunships can be affected by these nades like in the earlier versions. Thanks.

**Comment by Firmeteran** [comment]
> Garrys.Mod.x64.2024-07-29.13-56-03.mp4
> 
> So, I've disabled the workshop version, and installed the current git version but I think the problem still persists on gunships. The grenades hit the gunship NPC but couldn't destroy it. Funny that helicopter NPC still can be destroyed.
> 
> Maybe you can look into the lua files of the GL nades, see if you can edit them so gunships can be affected by these nades like in the earlier versions. Thanks.

https://github.com/user-attachments/assets/d803845d-b559-487e-b25c-f7053c5f667a

Tried few times, everything seems fine on my end (using git ver).
Maybe there's _some_ mod altering that, I'd recommend you to disable all mods you installed and enable only the weapon base and this pack (also it's other requirement). See if the problem still occurs or not.
If there's one, kindly send it here 🙏

**Comment by Firmeteran** [comment]
> So I finally found out what caused this issue. It's [this addon made by Zippy originally but edited by someone else](https://steamcommunity.com/sharedfiles/filedetails/?id=3139359330)
> Garrys.Mod.x64.2024-07-29.16-37-19.mp4
> 
> Now I can kill gunships with GL after disabling that addon. Not sure what made that addon, causing the GL to malfunction.

Ok, I've heard a lot **that** mod cause troubles even to other addons too (not sure which ones).
Don't know why you must have that installed, maybe except fixing some error people are mentioned in those comments.
If it's serves no purpose to your gameplay, I'd recommend to just uninstall that mod.

**Comment by highblaz97** [comment]
Well initially I installed that because I remember one of Zippy's addon needed addon that I showed you above to work by installing that. I think I no longer needed that thing so now it's uninstalled.
