### ISSUE TITLE
Broken UBGL crosshair

### ISSUE THREAD

**Issue by ColonelRedips** [CurlySparkle/ARC9-COD2019#106]
Not sure whether to post this in main or shared, but whatever. This affects all UBGL attachments. MGL is not bugged though.
![20240726120222_1](https://github.com/user-attachments/assets/79e7d103-a7f5-4ca8-a628-5fcbbc4aefb7)
![20240726120227_1](https://github.com/user-attachments/assets/b9376c2a-cb22-4823-a814-00e4d89c4972)

**Comment by MokaAkashiya85** [comment]
Are you using the Workshop build of ARC9? Try using the Github version instead.

**Comment by ColonelRedips** [comment]
Yep I was using the workshop build, and installing Git version did the trick. Tysm 👍

**Comment by CurlySparkle** [comment]
yeah the arc9 update hasn't been. pushes to the workshop yet
