### ISSUE TITLE
x16's featherweight full auto only works in multiplayer + all midtrak & rangemaster scope reflex sights have missing textures

### ISSUE THREAD

**Issue by DaBestGitHubber** [CurlySparkle/ARC9-COD2019#108]
![image](https://github.com/user-attachments/assets/30b77241-01f6-4751-90cf-49e2f24bab95)

**Comment by CurlySparkle** [comment]
scope's been fixed as for the featherweight problem, sadly this works fine on my side, i can fully auto with it on singleplayer so not sure about what the problem is
