### ISSUE TITLE
SCAR: SoH + UBGL + 20- or 30-round empty reload animations have a floating bolt

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#109]
When you perform an empty reload while having the SoH perk, UBGL, and either the 20- or 30-round 7.62 NATO mags equipped, the SCAR's bolt floats. The 30-Round 5.56 mag is not affected by this.

https://github.com/user-attachments/assets/c490de83-4eed-4710-b3ee-5db230080e7a

**Comment by CurlySparkle** [comment]
hopefully should be fixed now
