### ISSUE TITLE
Weapons hanging up empty

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#11]
when your weapon is empty, there is a little mistake while you are reloading.Pay attention to the pistol sleeve when you are reloading(empty reloading),especially pistols.

**Comment by CurlySparkle** [comment]
uhh can you show a vid about that cuz i have no idea what you mean by pistol "sleeve"

**Comment by mwxmwh** [comment]
I can't send videos in github(the videos must smaller than 10MB)

**Comment by mwxmwh** [comment]
https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/c94b6469-0641-4704-b00f-f87294ee6910

pay attention

**Comment by mwxmwh** [comment]
sleeve will back for one seconds

**Comment by mwxmwh** [comment]
like earlier third person pistol animations.

**Comment by CurlySparkle** [comment]
hopefully should now be fixed on next update
