### ISSUE TITLE
m1911's (and its akimbo variant) 15 round mag isn't aligned and scaled properly

### ISSUE THREAD

**Issue by DaBestGitHubber** [CurlySparkle/ARC9-COD2019#110]
![image](https://github.com/user-attachments/assets/436b012c-217e-4bec-95f5-f251fa9d01aa) 
![image](https://github.com/user-attachments/assets/aed50526-0941-4de7-8897-4b537bd7273c)

**Comment by CurlySparkle** [comment]
fixed on next update
