### ISSUE TITLE
Sounds are broken in mulitplayer

### ISSUE THREAD

**Issue by burner194680** [CurlySparkle/ARC9-COD2019#111]
When in multiplayer, shooting while moving breaks sound. Sounds like airsoft when bug happens. happens with every weapon.
Please fix :)

**Comment by CurlySparkle** [comment]
do you have any footsteps changer mods? for some reason certain mods will end up conflicting with the sounds, not sure why, i can't do much about it either.

**Comment by burner194680** [comment]
Nope, I have even retarted the game  with no mods and the arc9 mw19 weapons sound bugs are still there

**Comment by CurlySparkle** [comment]
this been now fixed
