### ISSUE TITLE
Gun Homunculus

### ISSUE THREAD

**Issue by qweryqwq** [CurlySparkle/ARC9-COD2019#112]
Sometimes the guns will combine with eachother, like akimbo revolver and p90 being in the same slot. Here is an example of the issue. This is supposed to be the 725 shotgun
![20240816220554_1](https://github.com/user-attachments/assets/95e4a37b-129c-41ed-9006-0ce65a3ba2b2)

**Comment by CurlySparkle** [comment]
issue is that you did not get the arc9 mw19 pack and instead you tried using mwb with arc9, mwb is its own base and weapons, arc9 mw19 is its own weapon pack and requires arc9 base to work
