### ISSUE TITLE
LVS issues

### ISSUE THREAD

**Issue by Scorpanelo** [CurlySparkle/ARC9-COD2019#113]
any missles from rpg,mgl,strela,etc... (eny which creates explosion), when u firing and ammo try to hit LVS based vehicle, ammo just disappeared

**Comment by CurlySparkle** [comment]
Can you show a video about this problem to be sure? because we don't really use LVS stuff

**Comment by Scorpanelo** [comment]
https://github.com/user-attachments/assets/d100e5d1-f2ab-4004-b03d-3ccc3cb1f7d8

sure

**Comment by CurlySparkle** [comment]
i see, i think i know what the problem is, will push a hotfix soon to the workshop that hopefully fixes that problem, if not, let me know here

**Comment by Scorpanelo** [comment]
nice, rn all good working, thx
