### ISSUE TITLE
add MORS from MWIII

### ISSUE THREAD

**Issue by MannMakerStudio17** [CurlySparkle/ARC9-COD2019#114]
the MORS is a railgun in Advanced Warfare, it also appears in rebooted MW3

will include
- Custom Muzzleflash and Tracer
- Sticker, Camo and Charm Support
- Aftermarket Parts
- Accurate Stats and Original Sound

question: why you remove G3 and FSS Hurricane in the previous packs ?
another question: is there possible rebooted mw2/3 arc9 pack in the future ?

**Comment by CurlySparkle** [comment]
this is an issue page not a requesting section, as for why the g3 and fss hurricsne were removed was because they couldn't fit since the pack was meant for mw19 weapons only and also the g3 isn't an official weapon
