### ISSUE TITLE
all akimbo weapons' receiver slot are positioned in a random spot on the map

### ISSUE THREAD

**Issue by DaBestGitHubber** [CurlySparkle/ARC9-COD2019#116]
![image](https://github.com/user-attachments/assets/01780682-8873-4a90-a7f2-82b56322039b)
![image](https://github.com/user-attachments/assets/eb4823c4-f2d5-48ff-80a6-d7cb98729a2d)
![image](https://github.com/user-attachments/assets/59664439-f7a0-4ac5-8d36-95b1519b8a47)

**Comment by CurlySparkle** [comment]
hopefully should be fixed on next commit
