### ISSUE TITLE
M4A1 Stickers are broken and animation problems with RAM-7

### ISSUE THREAD

**Issue by ner194680** [CurlySparkle/ARC9-COD2019#117]
First one is self explanatory 
![4000_212](https://github.com/user-attachments/assets/cfe72d42-8079-4681-abbc-7dae9c0f6b03)
![4000_211](https://github.com/user-attachments/assets/912bb9d2-8138-4f57-99dc-b618b54e0c7a)

Reloading for the RAM-7 causes the pinkie to get unnaturally long and dislocates the index finger. Video for proof.
https://github.com/user-attachments/assets/9c83d6ee-0796-4b42-be89-3e9ac4b6c07c

**Comment by CurlySparkle** [comment]
m4 sticker should be fixed as for the ram-7 anims too on next commit.
