### ISSUE TITLE
New bug about M19

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#12]
https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/1a89bdda-5db5-4bdf-9c31-58934aed8d84

https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/ad2f30d0-b355-46d5-984a-24fc8381cc88

check the video and you will find problem soon

**Comment by CurlySparkle** [comment]
fixed
