### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#23]
After the latest update, ARC9 begins to appear problems and I can't use mw2019 weapons.

**Comment by Firmeteran** [comment]
Hi, can you elaborate more about it?
Cus, everything still works well on my end, maybe _could_ be only on your end

**Comment by mwxmwh** [comment]
I found that all the weapons work well(I tested again just now) except 1911

**Comment by Firmeteran** [comment]
Ok. Btw, if there's any error about it, feel free to copy 'em in here,
so we can know what's the cause of it

**Comment by mwxmwh** [comment]
![Desktop Screenshot 2024 02 17 - 17 32 20 22](https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/2127f06d-8492-4c6b-b329-194ceda9b79b)

**Comment by mwxmwh** [comment]
[ARC9 Weapon Base] lua/weapons/arc9_base/sh_mergeslots.lua:17: attempt to index local 'slot' (a userdata value)
    1. BuildMergeSlots - lua/weapons/arc9_base/sh_mergeslots.lua:17
        2. BuildSubAttachments - lua/weapons/arc9_base/sh_subatts.lua:235
            3. ReceiveWeapon - lua/weapons/arc9_base/sh_net.lua:127
                4. func - lua/arc9/server/sv_net.lua:42
                    5. unknown - lua/includes/extensions/net.lua:38[ARC9 Weapon Base] lua/weapons/arc9_base/cl_presets.lua:434: attempt to index local 'tbl' (a userdata value)
    1. PruneUnnecessaryAttachmentDataRecursive - lua/weapons/arc9_base/cl_presets.lua:434
        2. GetPresetJSON - lua/weapons/arc9_base/cl_presets.lua:482
            3. GeneratePresetExportCode - lua/weapons/arc9_base/cl_presets.lua:489
                4. SavePreset - lua/weapons/arc9_base/cl_presets.lua:237
                    5. PostModify - lua/weapons/arc9_base/sh_attach.lua:123
                        6. Attach - lua/weapons/arc9_base/sh_attach.lua:22
                            7. unknown - lua/weapons/arc9_base/cl_customize_ui_bottombar.lua:266[ARC9 Weapon Base] lua/weapons/arc9_base/sh_mergeslots.lua:17: attempt to index local 'slot' (a userdata value)
    1. BuildMergeSlots - lua/weapons/arc9_base/sh_mergeslots.lua:17
        2. BuildSubAttachments - lua/weapons/arc9_base/sh_subatts.lua:235
            3. ReceiveWeapon - lua/weapons/arc9_base/sh_net.lua:127
                4. func - lua/arc9/client/cl_net.lua:7
                    5. unknown - lua/includes/extensions/net.lua:38[ARC9 Weapon Base] lua/weapons/arc9_base/sh_mergeslots.lua:17: attempt to index local 'slot' (a userdata value)
    1. BuildMergeSlots - lua/weapons/arc9_base/sh_mergeslots.lua:17
        2. BuildSubAttachments - lua/weapons/arc9_base/sh_subatts.lua:235
            3. LoadPresetFromTable - lua/weapons/arc9_base/cl_presets.lua:95
                4. swepLoadPreset - lua/weapons/arc9_base/cl_presets.lua:212
                    5. unknown - lua/weapons/arc9_base/sh_think.lua:209[ARC9 Weapon Base] lua/weapons/arc9_base/sh_mergeslots.lua:17: attempt to index local 'slot' (a userdata value)
    1. BuildMergeSlots - lua/weapons/arc9_base/sh_mergeslots.lua:17
        2. BuildSubAttachments - lua/weapons/arc9_base/sh_subatts.lua:235
            3. ClientInitialize - lua/weapons/arc9_base/sh_init.lua:102
                4. unknown - lua/weapons/arc9_base/sh_init.lua:33[ARC9 Weapon Base] lua/weapons/arc9_base/sh_mergeslots.lua:17: attempt to index local 'slot' (a userdata value)
    1. BuildMergeSlots - lua/weapons/arc9_base/sh_mergeslots.lua:17
        2. BuildSubAttachments - lua/weapons/arc9_base/sh_subatts.lua:235
            3. unknown - lua/weapons/arc9_base/sh_init.lua:41
                4. Give - [C]:-1
                    5. unknown - gamemodes/sandbox/gamemode/commands.lua:899
                        6. unknown - lua/includes/modules/concommand.lua:54

**Comment by MokaAkashiya85** [comment]
For the record, I've had this happen on the MK2 Carbine for me, this exact same error. I have no clue what it even means.

**Comment by CurlySparkle** [comment]
fixed
