### ISSUE TITLE
NEW ISSUES

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#24]
I did a simple test.I tested all the weapons, only found 1911 and mk2 carbine have that mistake I have mentioned.
Also,I found double pistols and fists' close combat look strange.

**Comment by CurlySparkle** [comment]
you might have to explain by "look strange" on those two

**Comment by mwxmwh** [comment]
They are continuous, rather than hitting once with a single press.

**Comment by Firmeteran** [comment]
#23

**Comment by Firmeteran** [comment]
Derived from this #23

**Comment by mwxmwh** [comment]
If you hold left mouse,they just keep shaking instead of attack

**Comment by mwxmwh** [comment]
@Firmeteran You mean this problem is because of the same issues?(double pistols and fists)

**Comment by Firmeteran** [comment]
> @Firmeteran You mean this problem is because of the same issues?(double pistols and fists)

Kinda misread a bit, my bad. It's a different problem

**Comment by mwxmwh** [comment]
Hold right mouse will let double pistols shake

**Comment by CurlySparkle** [comment]
Can you show a video showing about these problems?

**Comment by mwxmwh** [comment]
https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/90dfde9a-0946-4adb-bda0-b6f060ee7d22

**Comment by mwxmwh** [comment]
And I think the second view of pistols is not very suitable,the 1911 looks smaller.In my opinion,the second view you made in your another page is perfect

**Comment by Firmeteran** [comment]
> Garrysmod.2024.02.19.-.10.44.57.01.2.mp4

I'm not sure, cus for me everything is works well as intended (not like yours). 
Idk what you've installed, cus afaik no one ever encountered smth like this

**Comment by mwxmwh** [comment]
https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/b5a12b58-eaf3-45da-857b-ec9249c5627a


> Garrysmod.2024.02.19.-.10.44.57.01.2.mp4

**Comment by mwxmwh** [comment]
> I'm not sure, cus for me everything is works well as intended (not like yours).
> Idk what you've installed, cus afaik no one ever encountered smth like this

I will check

**Comment by mwxmwh** [comment]
> > Garrysmod.2024.02.19.-.10.44.57.01.2.mp4
> 
> I'm not sure, cus for me everything is works well as intended (not like yours). Idk what you've installed, cus afaik no one ever encountered smth like this

No, I disabled all the mods but it still happens to me

**Comment by mwxmwh** [comment]
https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/535c38ef-856e-4e56-af5e-5ee5ef2b6431
I held the left mouse

**Comment by Firmeteran** [comment]
Yeah, no clue either, since I can't reproduce _your_ things.
Just make sure everything up-to-date I guess, try download the mod and maybe the weapon base using [GitHub Desktop](https://desktop.github.com/).

**Comment by mwxmwh** [comment]
You mean using the github version arc9 base?

**Comment by Firmeteran** [comment]
> You mean using the github version arc9 base?

Yes.

**Comment by mwxmwh** [comment]
problem solved, it's because of arc9
