### ISSUE TITLE
FR 5.56 aka FAMAS has inverse damage range curve

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#28]
I'm not sure if this is intentional, how it functions in MW2019, or if it's a bug/oversight. All other firearms' damage curves do more damage when closer to a target while the FR 5.56 does more damage the further the target is away rather than closer.

The screenshot below is of the weapon's base stats without any additional attachments, mods, or perks added to it.

![20240324000820_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/9eb316aa-3377-4b8f-b9d5-587403ff7342)

**Comment by CurlySparkle** [comment]
should be fixed in the next update
