### ISSUE TITLE
Lag when firing minigun

### ISSUE THREAD

**Issue by highblaz97** [CurlySparkle/ARC9-COD2019#29]
The minigun lags my PC very hard when firing, dropping my fps to 5-10, unlike other guns in this pack. I think it's likely due to **special bullet impact (SWEP.ImpactDecal = "FadingScorch")** and **explosions effects (SWEP.ExplosionEffect = "cod2019_muzzle_he2")**, slowing down my GMod. Can you make an option to enable/disable these custom special effects for the minigun? It would help players with lower-end PCs like mine.

**Comment by CurlySparkle** [comment]
most likely the ExplosionEffect causing the fps drop as i also noticed, but will be changed to a less problematic one eventually.

**Comment by highblaz97** [comment]
I've been thinking, maybe you can just remove these effects altogether. The minigun's effect combined with lag caused by any Gmod map will just make overall lag much worse. Removing them all might be the best option. Just my opinion.
