### ISSUE TITLE
Weapons are constantly stuck in the sprinting animation

### ISSUE THREAD

**Issue by PotPam** [CurlySparkle/ARC9-COD2019#30]

**Comment by CurlySparkle** [comment]
You need to explain more cuz i didn't notice a problem like that before, specially a recording also helps as well.

**Comment by PotPam** [comment]
I apologize for the very late response, I'll attempt to provide a proper recording later in the month if I am able to. My initial assumptions is that I either added the contents in wrongly, or they may be some sort of addon conflict. I intend to look further into it for now. Again, I apologize profusely for the delayed response, I was unfortunately unaware of your message until today. I'll attempt to keep a better track on my inbox in the future.

**Comment by CurlySparkle** [comment]
I tried checking with other people about this issue and so far some of them said that it could be related with movement mods, some might be outdated that would end up causing problems like this.

**Comment by CurlySparkle** [comment]
After multiple testing seems to be that when reducing the speed to less than 100 it breaks the wak/jog, not much that i can do 😢
