### ISSUE TITLE
Is the Model 680 supposed to be significantly weaker than the rest of the shotguns?

### ISSUE THREAD

**Issue by fanAllD** [CurlySparkle/ARC9-COD2019#32]
Its damage output is SIGNIFICANTLY lower than the other shotguns.

**Comment by CurlySparkle** [comment]
Currently the 680 is using a different damage setup for balance between ranges which then after those test it will be applied to the rest of the other shotguns, (before the shotguns were able to do full damage with just 1 pellet, they still do but the 680 is being changed to then be applied to the rest so they don't do about 80 dmg with just one pellet)
