### ISSUE TITLE
Launcher projectiles don't register their hits on Combine Gunships

### ISSUE THREAD

**Issue by syahmiasyraff02** [CurlySparkle/ARC9-COD2019#33]
As the title suggests, I have a problem with Launchers that their projectiles don't register their hits on Combine Gunships or to put it simply, they just go through like Combine Gunships don't even exist in the first place. Nearby explosions can still damage them though. Launcher projectiles from other ARC9 packs such as GSR don't have that problem.

https://github.com/CurlySparkle/ARC9-COD2019/assets/147134106/12755e7f-3cdd-4bd6-b0bd-10846656371d

**Comment by CurlySparkle** [comment]
Tried to get a workaround for this, hopefully this fixes that problem for now, its not perfect but at least it should work once i push it on the next commit
