### ISSUE TITLE
ARC9 Molotov Viewmodel Problem

### ISSUE THREAD

**Issue by aengus126** [CurlySparkle/ARC9-COD2019#42]
[I'm making this issue for a friend since he doesn't have github] 

The Molotov cloth is a little buggy when moving around and doesn't properly collide with the glass body. Instead it glitches through it. 

https://github.com/CurlySparkle/ARC9-COD2019/assets/78571650/04b7e2e9-8fcd-4c67-8242-853eec960276

**Comment by CurlySparkle** [comment]
Sadly there isn't much that i can do to fix it, this also seemed to be a conflict with ARC9 as for some reason it breaks the jiggle for some reason, which there was something i could do to fix it but sadly i cant 😢
