### ISSUE TITLE
Bugs and Suggestions with smoke grenades

### ISSUE THREAD

**Issue by syahmiasyraff02** [CurlySparkle/ARC9-COD2019#45]
BUGS

Whenever I stand inside the smokescreen from a thrown smoke grenade with enemy NPCs around me, I got spammed with the following error message in the console window:

[[ARC9] COD-MW2019] lua/entities/arc9_cod2019_smoke/init.lua:75: bad argument #1 to 'AddEntityRelationship' (Entity expected, got nil)
  1. AddEntityRelationship - [C]:-1
   2. unknown - lua/entities/arc9_cod2019_smoke/init.lua:75

SUGGESTIONS

Once upon a time in the mod's development history, the smoke grenades actually blind enemy NPCs from seeing you whether you stand ahead or inside of the smokescreen. However, this feature caused unintended side effects such as physics props pushing away at high speeds and ARC9 grenade and launcher entities hit the smokescreen "wall." Nowadays, the smoke grenades only blind enemy NPCs when you're standing in the smokescreen. I would like to have the old smoke grenade feature back, this time without the unintended bugs, if that's even possible.

**Comment by CurlySparkle** [comment]
Back in that development history the smoke grenade did not had the feature where it could blind npcs, this was just added recently as for the problems with the collision thats being worked on.
