### ISSUE TITLE
Launcher projectiles disappear when hitting LVS vehicles

### ISSUE THREAD

**Issue by venturized** [CurlySparkle/ARC9-COD2019#46]
Launcher projectiles get destroyed upon hitting an LVS entity.
No explosion or damage is caused.
Nothing related gets printed to console.

Affected SWEPs / Attachments are:

- JOKR
- MGL-32
- PILA
- RPG-7
- Strela-P
- Crossbow (Still causes damage)
- M203 40mm Flash
- M203 40mm High-explosive
- M203 40mm Incendiary
- M203 40mm Smokescreen

All of these were tested with only these addons enabled:

- [LVS] - Framework
- [LVS] - Helicopters
- [LVS] - Cars
- ARC9 Weapon Base
- [ARC9] COD-MW2019
- [ARC9] COD-MW2019: Shared Pack

https://github.com/CurlySparkle/ARC9-COD2019/assets/153086001/5f3c765c-ef97-455d-8596-c63ddf65b2de

**Comment by CurlySparkle** [comment]
I'll try to see what's wrong since honestly, I have no idea how even lvs vehicles even work lol

**Comment by CurlySparkle** [comment]
Found the problem, tried doing some changes, hopefully this solves that problem either way i ain't no lua person so apologies if its not perfect 😢
