### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by morbocchi** [CurlySparkle/ARC9-COD2019#5]
Been tinkering with this awesome pack recently and would like to know how I can properly use Darsu's EFT attachments with this pack. I've been successful so far with optics and minor stuff but when it came to the stocks they were facing sideways. Probably just my dumdum brain but if you know what I might be doing wrong I'd appreciate it. 

Thank you and keep up the great work with this!

**Comment by CurlySparkle** [comment]
You would probably have to rotate the attachment that adds the support for the EFT stocks, i'd suggest using ATT.ModelAngleOffset so you can rotate around the attachment.
