### ISSUE TITLE
PILA and launchers

### ISSUE THREAD

**Issue by guyguyga** [CurlySparkle/ARC9-COD2019#52]
The pila CAN kill combine gunships if they hit them and explode just right, but often times, their homing rockets will bug out and zig-zag across the gunship harmlessly, doing no damage. They need better hit detection so that they explode when near a gunship instead of having to hit the gunship due to the lack of a hitbox for the NPC. The JOKR doesn't have that issue as much.

Also, where is the Pila's scope? It's just gone. The older GitHub versions still have it.

**Comment by Firmeteran** [comment]
Hi, we're gonna take a look at the issue.
But next time, please just listing the issues at once, rather than opening a new one.

Thank you.

**Comment by CurlySparkle** [comment]
This one should be fixed, hopefully
