### ISSUE TITLE
Origin12 and VLK Rogue: 12-round mag SoH reload animation errors

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#53]
When both the 12-round magazine and SoH perk are attached, it appears to reference the incorrect animations for both of the fast 12R mag reloads. Fast 12R reloads also reloads ammo as if there is a round already chambered.

https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/5d1e0dad-3119-49da-9229-727187b95c26

This also happens when a 12-round magazine and SoH are equipped on the VLK Rogue as well, but only for the fast empty reload.

https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/0670451f-d201-48e1-9713-7a8bf93894ae

**Comment by CurlySparkle** [comment]
should be fixed now hopefully
