### ISSUE TITLE
pkm muzzle flash behaving strangely + famas bipod icon missing texture

### ISSUE THREAD

**Issue by IncognitoLilMan** [CurlySparkle/ARC9-COD2019#54]
whenever you add any sort of barrel modification on the pkm and start moving while firing, the muzzle flash doesn't line up with the barrel correctly

**Comment by CurlySparkle** [comment]
Weird it looks fine to me
https://github.com/CurlySparkle/ARC9-COD2019/assets/5094277/73810fc8-7ccb-40da-952b-e0bf7fdce0d3
