### ISSUE TITLE
Origin 12

### ISSUE THREAD

**Issue by guyguyga** [CurlySparkle/ARC9-COD2019#59]
When using the bipod on the origin 12, the view model of the character holds it incorrectly. Only happens on the bipod and not bipod foregrip.

**Comment by guyguyga** [comment]
Also, I know everyone uses TPIK, but for the people that aren't, could you make it so equipping a foregrip makes your world model use the smg1 holding animation? I've tested it, and the models line up very well for most. The only exception to this would be the side mounted foregrips.

**Comment by CurlySparkle** [comment]
> Also, I know everyone uses TPIK, but for the people that aren't, could you make it so equipping a foregrip makes your world model use the smg1 holding animation? I've tested it, and the models line up very well for most. The only exception to this would be the side mounted foregrips.

If its possible then sure, if you already know how to make this possible then you can also help by submitting a pull request of that change, either way most of that stuff related with attachments are on the shared git.

**Comment by CurlySparkle** [comment]
origin bug is now fixed on next commit
