### ISSUE TITLE
after 6.6. update, some issues are accured

### ISSUE THREAD

**Issue by kid219** [CurlySparkle/ARC9-COD2019#63]
(sorry for poor eng)
after latest update,
1. crossbow bolts fired by NPCs goes random direction, but never goes forward.
2. When every Hostile NPC targets me, unless I'm very close(around 3 or 4yd) to them, they can't hit me. bullets are always pass to my left side. I tried NPCs fighting each other, and their hit rate is the same as usual. but if their taget is me, they never hit me
3. A bullet fired by another player/NPCs looks like to be fired out of midair to the left of the gun's muzzle(relative to the shooter). Muzzle flash is normal. 
4. The impact group is formed slightly oriented to the right. (I don't know how to say this word in English. Original text: Tanchak-gun, 탄착군)
5. When I throw a Molotov cocktail, it flies normally, but the graphics make it look like it's dropping at my feet.
6. When throw any throwing weapons, the frame rate decreases.
7. When trying to give a gun to a player from the spawn menu, there will be a few seconds of lag before the gun is give to me

**Comment by kakahost** [comment]
Checked it. This is not addon conflict. All this is true.

**Comment by CurlySparkle** [comment]
1, 2, 3, 4, 6 and 7 seem to be either game or base related.
5 its been fixed finally.
