### ISSUE TITLE
MP5 lightweight barrel issue

### ISSUE THREAD

**Issue by kakahost** [CurlySparkle/ARC9-COD2019#64]
![image](https://github.com/CurlySparkle/ARC9-COD2019/assets/95466263/34881f36-4450-4291-992e-abf34ce6ec5b)
![image](https://github.com/CurlySparkle/ARC9-COD2019/assets/95466263/189a7e80-0375-4f15-a3ac-e63c9a403ab2)

**Comment by CurlySparkle** [comment]
fixed
