### ISSUE TITLE
AK47 75-round drum mag drops from incorrect mag in animation

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#69]
This only occurs with the normal empty reload animation. It drops from the correct mag in the SoH tactical and empty reload animations.

https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/147a9afb-c200-4239-bf33-80dc6f097064

**Comment by CurlySparkle** [comment]
god i hate when this happens, hopefully it should be fixed now
