### ISSUE TITLE
1911's mistake

### ISSUE THREAD

**Issue by mwxmwh** [CurlySparkle/ARC9-COD2019#7]
Alt view will change when you shooting.And the photo shows another problem.
![20230726104516_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/116985165/4d35655d-edcb-444e-aa68-2b91d169d05c)

**Comment by mwxmwh** [comment]
These is two problems I mentioned

**Comment by CurlySparkle** [comment]
well one of it should be fixed as for the first one with the (Alt view will change when you shooting), i didn't really get that problem im afraid.
