### ISSUE TITLE
grenades and throwables issue in multiplayer

### ISSUE THREAD

**Issue by DaBestGitHubber** [CurlySparkle/ARC9-COD2019#75]
c4 has an invisible detonator, claymore doesn't have an explosion effect once it detonates (along with the c4), and throwing knife multiplies its ammo once thrown and picked up

**Comment by CurlySparkle** [comment]
if you meant that theres no detonator in third person its because its not possible to setup two different model holding, and theres also bugs when holding the detonator when tpik is enabled so it had to be disabled, as for the claymore with no effct, it should been fixed already
