### ISSUE TITLE
m4 magazine rounds and shield

### ISSUE THREAD

**Issue by guyguyga** [CurlySparkle/ARC9-COD2019#76]
The rounds start disappearing near the end of the magazine, rather than disappearing near the beginning. They still show until you nearly empty the entire magazine. This is incorrect. 

The ammo you see is the bottom of the magazine. Therefore, they start disappearing when you start firing. This can be seen in the M13 rifle. That one correctly displays what happens to a magazine when you start to empty it. 

If you zoom into the magazine, you can see where it's marked at 25 rounds, 15 rounds, and 5 rounds. 

A full mag will have a full window. 
A magazine with 25 rounds will have an almost full window. 
A magazine with 15 will have roughly half a window. 
A magazine with less than 5 rounds will have an empty window.

**Comment by guyguyga** [comment]
It seems the magazine has exactly 16 bones for bullets. I don't know if there's more, but you have to move the bones down so that when full, all 16 appear in the window. Right now they're too high up.

**Comment by guyguyga** [comment]
Also, poison headcrabs can poison you even with a shield equipped despite doing zero damage.

**Comment by CurlySparkle** [comment]
> The rounds start disappearing near the end of the magazine, rather than disappearing near the beginning. They still show until you nearly empty the entire magazine. This is incorrect.
> 
> The ammo you see is the bottom of the magazine. Therefore, they start disappearing when you start firing. This can be seen in the M13 rifle. That one correctly displays what happens to a magazine when you start to empty it.
> 
> If you zoom into the magazine, you can see where it's marked at 25 rounds, 15 rounds, and 5 rounds.
> 
> A full mag will have a full window. A magazine with 25 rounds will have an almost full window. A magazine with 15 will have roughly half a window. A magazine with less than 5 rounds will have an empty window.

This cannot be fixed because the weapon bones only have a max of 16 bullet bones in the magazine (this also the same thing in mwb), as for the shield this also cannot be fixed because the damage is still being happening when you get hit but it doesn't give you any dmg whatsoever so youll still seeing the screen effects.

**Comment by guyguyga** [comment]
16 bullet bones is still a very generous amount. Is there any way to move the bones down? The bones seem to be..... misaligned.
