### ISSUE TITLE
[BUG] Equiping any magazine on AK-47 then select no stock makes the charater do iraqi reload animation with stock while the AK-47 doesnt have stock on

### ISSUE THREAD

**Issue by C1TY17** [CurlySparkle/ARC9-COD2019#77]
Iraqi Animation With Removed Stock
![20240618153559_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/139605750/e7cfa87e-45da-4629-87d3-f45e0374515d)
![20240618153653_2](https://github.com/CurlySparkle/ARC9-COD2019/assets/139605750/53e4d5d7-3077-46a9-a788-72a76b82177b)
Iraqi Animation Without Removing Stock
![20240618153613_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/139605750/7ae833dc-7c8f-41c5-83c3-99c53ec6caba)
![20240618153642_2](https://github.com/CurlySparkle/ARC9-COD2019/assets/139605750/05ce4f1f-4cc9-499a-927a-deee652c2fcd)

This is how the character should reload with and without stock on AK (example shown on MWII)
https://youtu.be/nAS4LEqgLeQ?si=zNgW3tUROSjcMJdQ

**Comment by CurlySparkle** [comment]
Can't be fixed because the animation is depended on the magazine type hence you are using the 5.45×39 mag types.

**Comment by MokaAkashiya85** [comment]
This issue has been fixed as of https://github.com/CurlySparkle/ARC9-COD2019/commit/2ea050b563531a64e8007afd4d78af4e49b7d8c6
