### ISSUE TITLE
Kar98k, MK2 Carbine don't have their cartridges hidden when not reloading.

### ISSUE THREAD

**Issue by xVal429** [CurlySparkle/ARC9-COD2019#8]
Couldn't figure out how to actually fix this, since the typical route of 'SWEP.HideBones' does not seem to do anything on these two in particular.
![image](https://github.com/CurlySparkle/ARC9-COD2019/assets/68100216/79ac592e-3088-47d2-a4f8-6be69208d3ec)
![image](https://github.com/CurlySparkle/ARC9-COD2019/assets/68100216/b3039d91-cbed-4604-9657-8910e5dfb8df)

**Comment by CurlySparkle** [comment]
Seems fixed now after changing ReloadHideBonesFirstPerson to false on both weapons, these settings can be quite janky and get buggy if they aren't quite figured out sadly for me these is just stuff im not experienced with.
