### ISSUE TITLE
ISO 50-Round drum mag has no physics mesh and Throwing Knife pick-up bug

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#87]
Two minor issues I discovered:

-Picking up thrown knives gives 4 additional knives instead of 1.

-ISO's 50-Round drum magazine has no physics mesh, thus preventing it from spawning during empty and SoH reloads.
![20240629203940_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/8f0ca4dc-d183-4c5d-b7b8-852aeaac1bf8)

**Comment by CurlySparkle** [comment]
hopefully should be fixed now.
