### ISSUE TITLE
Is it possible to get view models on directx 8 or lower?

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [CurlySparkle/ARC9-COD2019#9]
View models are broken on dx8 and dx7. They don't get displayed at all.

**Comment by Kamilkampfwagen-II** [comment]
Is it caused by lack of shaders or such limitation of older dx versions?

**Comment by CurlySparkle** [comment]
sadly yeah, using an much older version of it ends up causing more heavy issues specially these included, besides that, you should mostly be at least on dx9 so even standard gmod can work properly.
