### ISSUE TITLE
Aim-Op UV Mapping Issue & Knife ammo bug

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#93]
1. UV Mapping error, or incorrect texture error is present on the high profile version of the "Aim-Op" reflex sight. 

![20240706195203_1](https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/bb929329-91a1-4e95-ba12-26af1c513808)

2. The throwing knife ammo bug appears to still be present. Walking over thrown knives to pick them up does not replenish its ammo pool, and pressing 'E' on them replenishes a different ammo pool.
**Through testing, changing "SWEP.ClipSize" to 0 temporarily fixes the issue for the current session. When starting a new session, however, the bug returns.**

https://github.com/CurlySparkle/ARC9-COD2019/assets/41251184/dfe87166-9cc7-4454-99c3-dd97c2b7f69a

**Comment by CurlySparkle** [comment]
fixed hopefully
