### ISSUE TITLE
a couple of npc weapon issues, and some suggestions too maybe

### ISSUE THREAD

**Issue by hn6awos** [CurlySparkle/ARC9-COD2019#95]
**Bugs**
NPCs that spawn with a .357 or a Crossbow spawn with an invisible "MW2019 Base" or a "MW2019 Base Nade" weapon.
NPCs that spawn with an SMG1 don't have their weapons replaced.
Melees are treated like firearms instead of melees.
(Assuming this is a bug) Pretty much every weapon is treated like an SMG1, including pistols, launchers, sniper rifles, shotguns, etc.

https://github.com/user-attachments/assets/ec0acfd9-9d72-402b-9ca6-da02107efc10
https://github.com/user-attachments/assets/5589337e-8cb8-4632-8309-1626c9b4f5bd
https://github.com/user-attachments/assets/fc8d26c4-a318-444d-b0a6-a3040bcdf100
https://github.com/user-attachments/assets/5bfb05ed-fd40-4b42-9a41-6553ec761a6d
![image](https://github.com/user-attachments/assets/dccdf226-2a5f-4981-8351-01fb0f1c13d7)
![image](https://github.com/user-attachments/assets/838350d1-9b6b-4b17-b4eb-dbe409ce9b99)

**Suggestions**
If it's possible, blacklist the Akimbos from the NPC replacer setting.
Remove Crowbar replacers.
If it's possible, replacers for the Alyx Gun and Annabelle for the NPC replacer setting.

**Comment by CurlySparkle** [comment]
should be fixed on the next commit hopefully
