### ISSUE TITLE
Some issues: w_model missing textures, and some Multiplayer issues

### ISSUE THREAD

**Issue by MrFroglegs** [CurlySparkle/ARC9-COD2019#96]
1) I'm not sure if this is an ARC9 Base problem, or a problem with the MW2019 pack. In multiplayer, if you open the customization menu while moving, the weapons will play their walking animations. Tested on a Dedicated Server. This issue does not occur in single player.

https://github.com/user-attachments/assets/0e1ac37d-b9ac-4145-bedc-af6460ba6096

2) Another Multiplayer Issue:

When Gameplay > "No Ready Anims" Server variable is checked ( arc9_never_ready 1 ), the ready animation sounds will still play, even though the animations don't. This issue happens with all weapons. Tested on a Dedicated Server. This issue does not occur in single player.

https://github.com/user-attachments/assets/73c1e50b-0b12-4978-bb20-f951b45e0628

3) World models missing textures:

**w_eq_crossbow.mdl** and **w_rif_fal.mdl** have missing textures.

![20240712223033_1](https://github.com/user-attachments/assets/bb0b32f3-e987-4985-b2f7-0628e13f129e)

**Comment by CurlySparkle** [comment]
the world model should be fixed as for the the other two problems, sadly the no ready anim seems to be arc9's fault (as usual) as for the walking continuing on customization, not sure if this is the base's fault but will check either way eventually.
