### ISSUE TITLE
Missing Texture on CR-56 Intruder barrel + X16 Featherweight Slide locked to semi + missing screws on Renetti rear grips+ broken bodygroups on M4, SCAR 17, AS VAL, .357 and FAL

### ISSUE THREAD

**Issue by ColonelRedips** [CurlySparkle/ARC9-COD2019#99]
![20240719170156_1](https://github.com/user-attachments/assets/5cd7d99c-4f65-4907-aa31-d22604a78751)
![20240719200312_1](https://github.com/user-attachments/assets/76db7f80-b607-4fd1-ad2a-78d7d71b8ef3)
![20240719195753_1](https://github.com/user-attachments/assets/fb69fa50-7738-464c-9e1f-4de3def6e9a5)
![20240719195840_1](https://github.com/user-attachments/assets/a99d74f0-38e9-4566-a414-d368f3744ef7)
![20240719084508_1](https://github.com/user-attachments/assets/d7f7f11e-c44d-4c79-a58d-59abcecf714e)
![20240719200217_1](https://github.com/user-attachments/assets/65d09bb4-8236-456a-b223-a18c5a434abd)
![20240719200223_1](https://github.com/user-attachments/assets/7b7c521d-167f-416c-93a2-5bc89dc8228b)
![20240719195233_1](https://github.com/user-attachments/assets/fd147194-fa6b-43ea-9069-73e3019e0fe9)
![20240719195823_1](https://github.com/user-attachments/assets/371878ed-6226-4ce2-862d-4fb7782b2cb1)
![20240719195716_1](https://github.com/user-attachments/assets/ad2f39c2-5057-49e5-8bd7-f27c32fdef61)
![20240719195659_1](https://github.com/user-attachments/assets/90e528fb-1214-4837-8163-7133d300512b)

**Comment by CurlySparkle** [comment]
most of these should be now fixed
